# Generated by Django 3.0.9 on 2020-08-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='lists_list',
        ),
    ]
